version: '3.8'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "bot_app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5wOqJ2yO"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: on-failure
  bot:
    build: .
    command: "alembic upgrade head"
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - db
    links:
      - db
volumes:
  database_data:
    driver: local