"""new

Revision ID: 97ac6d7c3b47
Revises: 
Create Date: 2023-02-11 17:00:55.058989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ac6d7c3b47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
                    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('name_tg', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('wallet_buyer', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('user_id', name='buyer_pkey')
                    )
    op.create_table('good',
                    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('name_tg', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('name_good', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('quantity', sa.NUMERIC(), autoincrement=False, nullable=False),
                    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('rate', sa.NUMERIC(), autoincrement=False, nullable=False),
                    sa.Column('wallet', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False)
                    )
    op.create_table('seller',
                    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('name_tg', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('user_id', name='seller_pkey')
                    )
    op.create_table('admin',
                    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('wallet_admin', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('user_id', name='admin_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.drop_table('seller')
    op.drop_table('good')
    op.drop_table('buyer')
    # ### end Alembic commands ###
